services:
  app:
    build: ./app
    restart: always
    env_file: [.env.db, .env.app]
    expose:
      - 8000
    networks:
      - internal
      - default

  bot:
    build: ./bot
    restart: always
    env_file: .env.bot
    volumes:
      - bot_data:/data
    networks:
      - default
      - internal

  db:
    image: postgres:17.2
    restart: always
    shm_size: 512mb
    env_file: .env.db
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  caddy:
    build: ./caddy
    restart: always
    env_file: .env.caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile.dev:ro
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default
      - internal

networks:
  default:
  internal:
    internal: true

volumes:
  app_data:
  db_data:
  bot_data:
  caddy_data:
  caddy_config:
